#!/usr/bin/env ruby

`cp init.d_unicorn /etc/init.d/unicorn`
puts "Installed startup scripts."

`mkdir -p /usr/local/bin`
`cp cilantro /usr/local/bin`
`cp linode /usr/local/bin`
`cp site /usr/local/bin`
puts "Installed control scripts."

`mkdir -p /home/git/defaults`
`cp post-receive /home/git/defaults`
`cp post-receive-script /home/git/defaults`
`chmod o+x /home/git/defaults/post-receive-script`
`cp sample-site* /home/git/defaults`
puts "Installed defaults."

count = 0
Dir.glob("/home/git/repositories/*").each do |repo|
  `cat post-receive > #{repo}/hooks/post-receive`
  count += 1
end
puts "Installed post-receive into #{count} repositories."
